apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels:
    release: prom
spec:
  namespaceSelector:
    matchNames:
      - spot-kafka
  selector:
    matchLabels:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/name: kafka-cluster-kafka-exporter
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 15s
