apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spot-payment
  namespace: monitoring
  labels:
    release: prom
spec:
  namespaceSelector:
    matchNames:
      - spot
  selector:
    matchLabels:
      app: spot-payment
  endpoints:
    - targetPort: 8084
      path: /actuator/prometheus
