apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spot-user
  namespace: monitoring
  labels:
    release: prom
spec:
  namespaceSelector:
    matchNames:
      - spot
  selector:
    matchLabels:
      app: spot-user
  endpoints:
    - targetPort: 8081
      path: /actuator/prometheus
