apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: temporal
  namespace: monitoring
  labels:
    release: prom
spec:
  namespaceSelector:
    matchNames:
      - spot
  selector:
    matchLabels:
      app: temporal
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
