apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spot-ingress
  namespace: spot
  annotations:
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /$1  # 첫 번째 prefix 제거
spec:
  ingressClassName: nginx
  rules:
    - host: spot.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spot-gateway
                port:
                  number: 80
          - path: /kafka-ui
            pathType: Prefix
            backend:
              service:
                name: kafka-ui-svc
                port:
                  number: 80