apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-user
  namespace: spot
  labels:
    app: spot-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spot-user
  template:
    metadata:
      labels:
        app: spot-user
    spec:
      containers:
        - name: spot-user
          image: spot-registry.localhost:5111/spot-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: LOGGING_CONFIG
              value: "classpath:logback-spring.xml"
          envFrom:
            - secretRef:
                name: spot-secrets
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "800m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 150
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 30
      volumes:
        - name: app-config
          configMap:
            name: spot-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: spot-user
  namespace: spot
  labels:
    app: spot-user
spec:
  selector:
    app: spot-user
  ports:
    - name: http
      port: 8081
      targetPort: 8081
