apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spot-ingress
  namespace: spot
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: spot.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spot-gateway
                port:
                  number: 80

      # kafka
    - host: kafka.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-ui-svc
                port:
                  number: 80

      # temporal
    - host: temporal.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-ui-svc
                port:
                  number: 80