version: '3.8'

services:
  # --- Infrastructure: Database & Cache ---
  db:
    image: postgres:15-alpine
    container_name: local-postgres_db
    command: >
      postgres 
      -c max_connections=300
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
    environment:
      - POSTGRES_DB=myapp_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - spot-network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - spot-network

  # --- Infrastructure: Event Broker (Kafka) ---
  kafka1:
    image: apache/kafka:4.0.0
    container_name: kafka1
    restart: always
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:19093,2@kafka2:19093,3@kafka3:19093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:19093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka1:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: 'J9Xz7kQPRYyK8VkqH3mW5A'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: '-Xmx256M -Xms256M'
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'WARN'
      KAFKA_LOG4J_LOGGERS: 'kafka=WARN,state.change.logger=WARN'
    ports:
      - "9092:9092"
    volumes:
      - kafka-data-1:/var/lib/kafka/data
    networks:
      - spot-network
  
  kafka2:
    image: apache/kafka:4.0.0
    container_name: kafka2
    restart: always
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:19093,2@kafka2:19093,3@kafka3:19093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:19093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka2:29092,EXTERNAL://localhost:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: 'J9Xz7kQPRYyK8VkqH3mW5A'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: '-Xmx256M -Xms256M'
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'WARN'
      KAFKA_LOG4J_LOGGERS: 'kafka=WARN,state.change.logger=WARN'
    ports:
      - "9093:9093"
    volumes:
      - kafka-data-2:/var/lib/kafka/data
    networks:
      - spot-network

  kafka3:
    image: apache/kafka:4.0.0
    container_name: kafka3
    restart: always
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:19093,2@kafka2:19093,3@kafka3:19093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:19093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka3:29092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: 'J9Xz7kQPRYyK8VkqH3mW5A'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: '-Xmx256M -Xms256M'
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'WARN'
      KAFKA_LOG4J_LOGGERS: 'kafka=WARN,state.change.logger=WARN'
    ports:
      - "9094:9094"
    volumes:
      - kafka-data-3:/var/lib/kafka/data
    networks:
      - spot-network
  
  connect1: &connect-common
    container_name: connect1
    image: quay.io/debezium/connect:3.4.0.Final
    ports:
      - "8888:8083"
    env_file:
      - .env
    environment:
      CONNECT_CONFIG_PROVIDERS: 'env'
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: 'org.apache.kafka.common.config.provider.EnvVarConfigProvider'
      BOOTSTRAP_SERVERS: kafka1:29092,kafka2:29092,kafka3:29092
      GROUP_ID: "spot-connect-group"
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
      STATUS_STORAGE_TOPIC: "connect_status"
      CONFIG_STORAGE_REPLICATION_FACTOR: 3
      OFFSET_STORAGE_REPLICATION_FACTOR: 3
      STATUS_STORAGE_REPLICATION_FACTOR: 3
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      LOGGING_LEVEL: 'WARN'
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - db
    networks:
      - spot-network

  connect2:
    <<: *connect-common
    container_name: connect2
    ports:
      - "8889:8083"
  
  connect-init:
    image: alpine:latest
    container_name: connect-init
    env_file:
      - .env
    depends_on:
      - connect1
      - connect2
    networks:
      - spot-network
    volumes:
      - ./connectors:/configs
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache curl jq && chmod +x /configs/register-connectors.sh && /configs/register-connectors.sh"]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8989:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: spot-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka1:29092,kafka2:29092,kafka3:29092'
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect-cluster
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: 'http://connect1:8083'
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_COM_PROVECTUS: WARN
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - spot-network
  
  # --- Temporal ---
  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.29.3
    ports:
      - "7233:7233"
    environment:
      - DB=postgres12
      - POSTGRES_SEEDS=${DB_HOST}
      - DB_PORT=5432
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PWD=${SPRING_DATASOURCE_PASSWORD}
      - DBNAME=spot_temporal
      - VISIBILITY_DBNAME=spot_visibility
      - SKIP_DB_CREATE=false
      - SKIP_SCHEMA_SETUP=false

      - POSTGRES_TLS_ENABLED=true
      - POSTGRES_TLS_DISABLE_HOST_VERIFICATION=true
      - SQL_TLS_ENABLED=true
      - SQL_HOST_VERIFICATION=false

      - ENABLE_ES=false
      - SKIP_DEFAULT_NAMESPACE_CREATION=false
      - LOG_LEVEL=warn
    depends_on:
      - db
    networks:
      - spot-network


  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:latest
    ports:
      - "8233:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8233
    depends_on:
      - temporal
    networks:
      - spot-network

  # --- Application Services ---
  spot-gateway:
    build:
      context: ./spot-gateway
      dockerfile: Dockerfile
    container_name: spot-gateway
    environment:
      - LOGGING_LEVEL_ROOT=WARN
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    depends_on:
      - redis
      - spot-user
      - spot-store
      - spot-order
      - spot-payment
    networks:
      - spot-network
    env_file:
      - .env

  spot-order:
    build:
      context: ./spot-order
      dockerfile: Dockerfile
    container_name: spot-order
    ports:
      - "8082:8082"
    volumes:
      - ./config:/config
    environment:
      - DB_HOST=db
      - SPRING_DATA_REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29092,kafka3:29092
      - SPRING_TEMPORAL_CONNECTION_TARGET=temporal:7233
      - LOGGING_LEVEL_ROOT=WARN
    depends_on:
      - db
      - redis
      - temporal
      - kafka1
      - kafka2
      - kafka3
    networks:
      - spot-network
    env_file:
      - .env

  spot-payment:
    build:
      context: ./spot-payment
      dockerfile: Dockerfile
    container_name: spot-payment
    ports:
      - "8084:8084"
    volumes:
      - ./config:/config
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - SPRING_DATA_REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29092,kafka3:29092
      - LOGGING_LEVEL_ROOT=WARN
    depends_on:
      - db
      - redis
      - kafka1
      - kafka2
      - kafka3
    networks:
      - spot-network

  spot-store:
    build:
      context: ./spot-store
      dockerfile: Dockerfile
    container_name: spot-store
    ports:
      - "8083:8083"
    volumes:
      - ./config:/config
    environment:
      - DB_HOST=db
      - SPRING_DATA_REDIS_HOST=redis
      - LOGGING_LEVEL_ROOT=WARN
    depends_on:
      - db
      - redis
    networks:
      - spot-network
    env_file:
      - .env

  spot-user:
    build:
      context: ./spot-user
      dockerfile: Dockerfile
    container_name: spot-user
    ports:
      - "8081:8081"
    volumes:
      - ./config:/config
    environment:
      - DB_HOST=db
      - SPRING_DATA_REDIS_HOST=redis
      - LOGGING_LEVEL_ROOT=WARN
    depends_on:
      - db
      - redis
    networks:
      - spot-network
    env_file:
      - .env

networks:
  spot-network:
    driver: bridge

volumes:
  kafka-data-1:
  kafka-data-2:
  kafka-data-3:
  postgres_data:
