apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: spot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.29.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7233
          env:
            # DB 연결 정보
            - name: DB
              value: postgres12
            - name: POSTGRES_SEEDS
              valueFrom:
                secretKeyRef:
                  name: spot-secrets
                  key: DB_HOST
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: spot-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: spot-secrets
                  key: SPRING_DATASOURCE_PASSWORD

            - name: DBNAME
              value: "spot_temporal"
            - name: VISIBILITY_DBNAME
              value: "spot_visibility"
            - name: SKIP_DB_CREATE
              value: "false"
            - name: SKIP_SCHEMA_SETUP
              value: "false"
            - name: ENABLE_ES
              value: "false"
            - name: SKIP_DEFAULT_NAMESPACE_CREATION
              value: "false"
            - name: LOG_LEVEL
              value: "warn"

#            # RDS 연결
#            - name: POSTGRES_TLS_ENABLED
#              value: "true"
#            - name: POSTGRES_TLS_DISABLE_HOST_VERIFICATION
#              value: "true"
#            - name: SQL_TLS_ENABLED
#              value: "true"
#            - name: SQL_HOST_VERIFICATION
#              value: "false"

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "750m"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: spot
spec:
  type: ClusterIP
  selector:
    app: temporal
  ports:
    - port: 7233
      targetPort: 7233

