apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: spot-kafka
spec:
  kafka:
    version: 4.0.0
    metadataVersion: "3.7-IV4"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: controller
        port: 9093
        type: internal
        tls: false
    config:
      process.roles: "broker,controller"
      offsets.topic.replication.factor: 1 # 3
      transaction.state.log.replication.factor: 1 # 3
      transaction.state.log.min.isr: 1  # 2
      default.replication.factor: 1 # 3
      min.insync.replicas: 1  # 2
      auto.create.topics.enable: "true"
      num.partitions: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
