apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: spot
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  
  postgresql:
    parameters:
      max_connections: "300"
      max_replication_slots: "10"
      max_wal_senders: "10"
    pg_hba:
      - host replication admin 0.0.0.0/0 md5

  bootstrap:
    initdb:
      database: myapp_db
      owner: admin
      secret:
        name: spot-secrets

  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  # 이 섹션이 있으면 CNPG가 논리적 복제 기능을 준비합니다.
  replicationSlots:
    highAvailability:
      enabled: true