apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-dashboards-spot
    namespace: monitoring
    files:
      - ../base/monitoring/grafana/dashboards/spot-logs.json

  - name: grafana-dashboards-9578
    namespace: monitoring
    files:
      - ../base/monitoring/grafana/dashboards/9578.json

  - name: grafana-dashboards-15760
    namespace: monitoring
    files:
      - ../base/monitoring/grafana/dashboards/15760.json

  - name: grafana-dashboards-15757
    namespace: monitoring
    files:
      - ../base/monitoring/grafana/dashboards/15757.json

  - name: grafana-dashboards-15661
    namespace: monitoring
    files:
      - ../base/monitoring/grafana/dashboards/15661.json

  - name: grafana-dashboards-kafka-broker
    namespace: monitoring
    files:
      - ../base/monitoring/grafana/dashboards/kafka-broker.json

  - name: grafana-dashboards-temporal
    namespace: monitoring
    files:
      - ../base/monitoring/grafana/dashboards/temporal.json

      
  - name: grafana-dashboards-kafka-exporter
    namespace: monitoring
    files:
      - ../base/monitoring/grafana/dashboards/kafka-exporter.json
    
secretGenerator:
  - name: spot-secrets
    namespace: spot
    envs:
      - ../../../.env
    options:
      disableNameSuffixHash: true

generatorOptions:
  disableNameSuffixHash: true