# --- Ingress ---
ingress:
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    alb.ingress.kubernetes.io/scheme: null
    alb.ingress.kubernetes.io/target-type: null
    alb.ingress.kubernetes.io/group.name: null

# domain
domain: localhost

# [2] 로컬 환경 Deployment 설정 (Global)
global:
  repository: spot-registry.localhost:5111