{{- range $key, $val := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $val.name }}
  labels:
    app: {{ $val.name }}
spec:
  replicas: {{ $.Values.global.replicas | default 1}}
  selector:
    matchLabels:
      app: {{ $val.name }}
  template:
    metadata:
      labels:
        app: {{ $val.name }}
    spec:
      containers:
        - name: {{ $val.name }}
          image: {{ $.Values.global.repository }}/{{ $val.name }}:latest
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $val.targetPort | default $val.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env.activeProfile }}
            - name: LOGGING_CONFIG
              value: {{ $.Values.env.loggingConfig }}
          envFrom:
            - secretRef:
                name: {{ $.Values.config.secretName }}

          # 리소스 설정
          resources:
            requests:
              cpu: {{ $.Values.global.requests.cpu }}
              memory: {{ $.Values.global.requests.memory}}
            limits:
              cpu: {{ $.Values.global.limits.cpu }}
              memory: {{ $.Values.global.limits.memory }}

          # 헬스 체크
          readinessProbe:
            httpGet:
              path: {{ $.Values.global.path }}
              port: {{ $val.targetPort | default $val.port }}
            initialDelaySeconds: {{ $.Values.global.readiness.initial }}
            periodSeconds: {{ $.Values.global.readiness.period }}
                      {{- if $val.timeoutSeconds }}
            timeoutSeconds: {{ $val.timeoutSeconds }}
                      {{- end }}
                      {{- if $val.failureThreshold }}
            failureThreshold: {{ $val.failureThreshold }}
                      {{- end }}
                      {{- if $val.successThreshold }}
            successThreshold: {{ $val.successThreshold }}
                      {{- end }}

          # 헬스 체크 (Liveness)
          livenessProbe:
            httpGet:
              path: {{ $.Values.global.path }}
              port: {{ $val.targetPort | default $val.port }}
            initialDelaySeconds: {{ $.Values.global.liveness.initial }}
            periodSeconds: {{ $.Values.global.liveness.period }}
                    {{- if $val.timeoutSeconds }}
            timeoutSeconds: {{ $val.timeoutSeconds }}
                    {{- end }}

          # 볼륨 마운트
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true

      volumes:
        - name: app-config
          configMap:
            name: {{ $.Values.config.configMapName }}
  {{- end }}